apiVersion: v2
name: arxsentinel
description: Real-time web server threat detection with Fail2Ban integration
type: application
version: 0.1.0
appVersion: "1.0.4"
home: https://github.com/mr-addams/arxsentinel
sources:
  - https://github.com/mr-addams/arxsentinel
maintainers:
  - name: mr-addams
    url: https://github.com/mr-addams
keywords:
  - security
  - fail2ban
  - nginx
  - intrusion-detection
  - prometheus
