// Code generated by tools/gen-plugins; DO NOT EDIT.

//go:build arx_tag && minimal

// ========================== Plugin blank-imports — minimal profile =======================
//   Side-effect registration of plugins declared in profiles/minimal.yaml.
//   Active only under build tags: -tags "arx_tag minimal".
//   See docs/architecture/adr/003-build-modularity.md and DECISIONS.md Flow 075.

package main

import (
	_ "github.com/mr-addams/arxsentinel/pkg/sink/stdout"
	_ "github.com/mr-addams/arxsentinel/pkg/source/stdin"
	_ "github.com/mr-addams/arxsentinel/pkg/source/syslog"
)
