// Code generated by tools/gen-plugins; DO NOT EDIT.

//go:build arx_tag && iot

// ========================== Plugin blank-imports — iot profile =======================
//   Side-effect registration of plugins declared in profiles/iot.yaml.
//   Active only under build tags: -tags "arx_tag iot".
//   See docs/architecture/adr/003-build-modularity.md and DECISIONS.md Flow 075.

package main

import (
	_ "github.com/mr-addams/arxsentinel/pkg/executor/cloudflare"

	// Plugin detectors (tree-shakeable side-effect registration, Flow 076)
	_ "github.com/mr-addams/arxsentinel/pkg/detector/overflow"
	_ "github.com/mr-addams/arxsentinel/pkg/detector/probe"

	_ "github.com/mr-addams/arxsentinel/pkg/sink/exec"
	_ "github.com/mr-addams/arxsentinel/pkg/sink/stdout"
	_ "github.com/mr-addams/arxsentinel/pkg/source/file"
	_ "github.com/mr-addams/arxsentinel/pkg/source/syslog"
)
